[project]
name = "data-viewer-streamlit"
version = "0.1.0"
description = "Tabular data viewer and cleaning tool built with Streamlit"
authors = [
    {name = "Ritesh Raj",email = "rajritesh03@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit (>=1.50.0,<2.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
